### ISSUE TITLE
What's your favorite animated gif?

### ISSUE THREAD

**Issue by ChrisMissal** [iheanyi/ama#7]
Currently, or all time, dealer's choice!

**Comment by iheanyi** [comment]
Ohhhh man, I've been busting this one out a lot recently: ![Giphy](http://media2.giphy.com/media/13AeIc8FQIMhfq/giphy.gif)

But my favorite one that I've been using for a minute, because Dave:
![Giphy](http://media1.giphy.com/media/qvRjLOs2SVPsk/giphy.gif)

**Comment by ChrisMissal** [comment]
:+1: :+1:
